project:
  type: website
  
website: 
  page-navigation: true
  favicon: img/brain_icon.svg
  reader-mode: true
  title: R-Guide
  sidebar:
    title: Sidebar
    logo: img/brain_icon.svg
    tools: 
      - icon: envelope
        href: "mailto:david.matischek@edu.uni-graz.at"
      - icon: github
        href: https://github.com/saiko-psych
    contents: 
      - text: "Overview"
        href: index.qmd
      - section: "Contents:"
        contents:
        - text: "About Page"
          href: about.qmd

comments:
  hypothesis: 
    theme: clean


format:
  html:
    theme: flatly
    toc: true